//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Product_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
            this.Product_Category_Detail = new HashSet<Product_Category_Detail>();
        }
    
        public int idProduct { get; set; }
        public string productName { get; set; }
        public string Sku { get; set; }
        public Nullable<int> stock { get; set; }
        public string productDescription { get; set; }
        public Nullable<int> idEditorial { get; set; }
        public Nullable<decimal> price { get; set; }
        public string productImage { get; set; }
        public HttpPostedFileBase productImageFile { get; set; }
        public virtual Editorial_ Editorial_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Category_Detail> Product_Category_Detail { get; set; }
    }
}
